site_name: Hussam — Notes
site_url: https://hussamhabib.com/notes/

theme:
  name: material
  features: []  # minimal chrome

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

docs_dir: docs
use_directory_urls: true        # <— matches USE_DIRECTORY_URLS in exporter

extra_css:
  - styles/win98.css
  - styles/notes.css

