site_name: Hussam — Notes
site_url: https://hussamhabib.com/notes/   # <- important

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - toc:
      permalink: true

docs_dir: docs
# This avoids some edge cases with asset paths under a subpath:
use_directory_urls: false

