site_name: Hussam — Notes
site_url: https://hussamhabib.com/notes/

theme:
  name: material
  features: []   # keep it minimal (you can add back later)

extra_css:
  - styles/win98.css   # <-- add this

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

docs_dir: docs
use_directory_urls: false

